name: flutter_smart_home
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/smart-house.png"
flutter:
  uses-material-design: true
  assets:
    - lib/icons/